### PR TITLE
Add PayPal integration resources

### PR DESCRIPTION
**Pull request by pamit**
This pull request adds resources for **PayPal integration** which are listed below. 
For more information about the APIs, refer to our [API reference](https://docs.fatzebra.com/reference).

```ruby
# PayPal resources & endpoints
FatZebra::Paypal::Order
FatZebra::Paypal::Capture
FatZebra::Paypal::Authorization
FatZebra::Paypal::Refund
FatZebra::Paypal::BillingAgreement

# Example:
refund = FatZebra::Paypal::Capture.refund('071-PPC-9JNQNPWCD3FSOHDG',  
  { 
     "amount": 1,
     "note_to_payer": "1 cent refund"
  }
)
```

### CODE REVIEW

**Review by jacksontrieu — APPROVED** [review]

**Review by sandhiyarajaraman — APPROVED** [review]
Looks Good to me.

**Review by sirjoe — APPROVED** [review]
LGTM

**Comment by amasses** [comment]
Looks Good. Thanks Payam.

**Review by amasses — APPROVED** [review]
👍🏻

**Pull request merged**
